Feature/this web getjsondata
webdoky/content-processor pull request #4
Opened 2022-10-28 22:03 UTC by undead404

2022-10-29 09:58 UTC, AdriandeCita requested changes
Виглядає круто, але є декілька зауважень)

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/environment/web.ts
> +export default class WebService {
Це наслідування принципу роботи Ярі? Особисто мені не дуже подобається мати взаємно вкладені об'єкти, і я б радше цього уникав. Але якщо так буде простіше - то вай нот.

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/environment/web.ts
> +  getJSONData(name: string): unknown {
Я б не хотів, щоб макроси запускали якісь файлові операції, особисто я б краще читав ці файли на етапі ініціалізації реєстру, і потім макрос отримував до них доступ через сам реєстр. Так, я бачу там нижче використовується кеш, тому з точки зору перформансу все має бути ок. Тож в принципі можна й так...

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/environment/web.ts
> +  link(uri: string, text: string, title: string, target: string): string {
Якщо подивишся по кодовій базі - я намагаюся виконувати всі операції зі вмістом на рівні АСТ, а не на рівні рядків. Це надійніше, і не потребує ручного екранування. Все, що стосується маніпуляцій з хтмл на рівні рядків - краще виносити на рівень макросів.

Я зазвичай такі речі просто вбудовував, як от тут https://github.com/webdoky/yari-ports/blob/master/lib/kuma/macros/domxref.js (зокрема тому, що загальна функція підтримує купу додаткових аргументів, і далеко не всі з них використовуються в конкретному макросі).
Але якщо є бажання виділити це в загальну функцію - це краще робити ось тут https://github.com/webdoky/yari-ports/tree/master/lib/kuma/utils.

За одно макроси не матимуть зворотної залежності на контент-процесор

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/environment/web.ts
> +  if (process.env.NODE_ENV === 'production') {
Я розумію, нащо МДН це робить, але для нас віключення цього кеша означає сповільнення роботи процесора під час тестування. Мені здається, для нас взагалі немає резону його відключати.

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/index.ts
> +    return Array.from(this.contentPages.keys())
Схоже, ця функція витягає взагалі всіх нащадків, а не лише дочірні сторінки. Нам це ок?

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/utils/escape-html.ts
> +export default function escapeHtml(unsafe: string): string {
це вже є в утилітах макросів https://github.com/webdoky/yari-ports/blob/master/lib/kuma/utils/html-escape.js.

2022-10-29 09:58 UTC, AdriandeCita commented on src/registry/utils/spaces-to-underscores.ts
> +export default function convertSpacesToUnderscores(input: string) {
same here https://github.com/webdoky/yari-ports/blob/master/lib/kuma/utils/spaces-to-underscores.js

2022-10-29 14:29 UTC, undead404 commented on src/registry/environment/web.ts
> +export default class WebService {
Так буде простіше, бо інакше доведеться закинути всі наворочені хелпери в один контекст

2022-10-29 14:31 UTC, undead404 commented on src/registry/environment/web.ts
> +  getJSONData(name: string): unknown {
А точно оптимально наперед вирішувати, що всі ці JSON файли повинні завантажуватися? Мені так не здається, на мою думку, мемоізація – то краще.

Можу запропонувати ввести хелпер "json", бо "web" – це якось незрозуміло, чому саме така назва

2022-10-29 14:36 UTC, undead404 commented on src/registry/index.ts
> +    return Array.from(this.contentPages.keys())
Не певен, поки приберу цей хелпер, а потім розбеермось

2022-11-09 22:36 UTC, AdriandeCita commented on src/registry/environment/json.ts
> +  // if (process.env.NODE_ENV === 'production') {
Плануєш, воно все ще може знадобитися?)

2022-11-09 22:39 UTC, AdriandeCita commented on src/registry/index.ts
> +        new Context(
Я вірно розумію, це буде кожного разу створювати новий примірник JsonService? Може тоді там кеш взагалі не потрібен, я не вірю, що він в межах однієї сторінки встигне розігнатись

2022-11-09 22:45 UTC, AdriandeCita commented on count_macros.py
> +from collections import Counter
Якщо в цій аналітиці є цінність - давай вносити в реєстр, чи краще навіть в раннер. Якщо ні - то чи є сенс взагалі тримати ці скрипти в репозиторії?

2022-11-09 22:49 UTC, AdriandeCita requested changes
В принципі, можна мержити, тілько з цим скриптом на пайтоні треба щось вирішити. Зауваження стосовно джейсон-сервіса може спричинити добрячий рефакторинг, але по суті це лише впливає на час відпрацювання контент-процесора, що імхо не критично

2022-11-28 12:43 UTC, undead404 commented on src/registry/environment/json.ts
> +  // if (process.env.NODE_ENV === 'production') {
Я б краще лишив як нотатку, що тут це було

2022-11-28 12:44 UTC, undead404 commented on src/registry/index.ts
> +        new Context(
Так, справді, виходить, треба винести той сервіс якось по-іншому

2022-11-30 23:09 UTC, AdriandeCita approved these changes

2022-11-30 23:10 UTC, merged